apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gjq4yfyzs-nodejs-gitops
  description: This is GitOps manifest for gjq4yfyzs-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=gjq4yfyzs-nodejs
    backstage.io/kubernetes-id: gjq4yfyzs-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gjq4yfyzs-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gjq4yfyzs-nodejs
